server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /etc/letsencrypt/live/explorerlewis.com/keystore.p12
    key-store-password:
    key-alias: lewis
  http2:
    enabled: true