spring:
  datasource:
    url: jdbc:h2:mem:game
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#Access local database console from http://localhost:80/h2-console
logging:
  level:
    root: DEBUG
server:
  port: 8081
  ssl:
    enabled: false

game:
  playlists:
    - World
    - North America
    - South America
    - Africa
    - Europe
    - Asia
    - Australia
    - Cities
  videos:
    - url: testUrl
      start-time: 40
      latitude: 90
      longitude: 90
      playlists:
        - Cities
        - World
    - url: testUrl2
      start-time: 50
      latitude: 90
      longitude: 90
      playlists:
        - Cities
        - World
    - url: testUrl3
      start-time: 50
      latitude: 90
      longitude: 90
      playlists:
        - World
        - Europe
    - url: testUrl4
      start-time: 50
      latitude: 90
      longitude: 90
      playlists:
        - World
        - Australia
